export const ERROR_MESSAGE = {
  EMAIL_OR_PASSWORD_INCORRECT: 'EMAIL_OR_PASSWORD_INCORRECT',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  USER_IS_EXISTED: 'USER_IS_EXISTED',
  FOR_BIDEN_RESOURCE: 'FOR_BIDEN_RESOURCE',
  REFRESH_TOKEN_INCORRECT: 'REFRESH_TOKEN_INCORRECT',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
};
